[project]
name = "aoc-2025"
version = "0.1.0"
description = "Advent of Code 2025 solutions in Python"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "shapely>=2.1.2",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

